"""add order confirmation tables

Written by hand rather than autogenerated: the target database is still behind
this branch's earlier migration, and alembic refuses to autogenerate against a
database that is not at head. Verified afterwards with
alembic.autogenerate.compare_metadata — see the commit message.

Revision ID: c244e1f8b7a0
Revises: b133d2455206
Create Date: 2026-08-31
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID

revision = "c244e1f8b7a0"
down_revision = "b133d2455206"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "order_confirmations",
        sa.Column("id", UUID(as_uuid=True), nullable=False),
        sa.Column("organisation_id", UUID(as_uuid=True), nullable=False),
        sa.Column("drive_file_id", sa.String(length=255), nullable=False),
        sa.Column("drive_modified_time", sa.String(length=64), nullable=True),
        sa.Column("file_name", sa.String(length=512), nullable=False),
        sa.Column("vendor", sa.String(length=255), nullable=True),
        sa.Column("season", sa.String(length=100), nullable=True),
        sa.Column("order_number", sa.String(length=100), nullable=True),
        sa.Column("currency", sa.String(length=10), nullable=True),
        sa.Column(
            "parsed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("line_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["organisation_id"], ["organisations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("drive_file_id"),
    )
    op.create_index(
        "ix_order_confirmations_organisation_id",
        "order_confirmations",
        ["organisation_id"],
    )

    op.create_table(
        "order_confirmation_lines",
        sa.Column("id", UUID(as_uuid=True), nullable=False),
        sa.Column("order_confirmation_id", UUID(as_uuid=True), nullable=False),
        sa.Column("style_number", sa.String(length=255), nullable=True),
        sa.Column("sku", sa.String(length=255), nullable=True),
        sa.Column("ean", sa.String(length=64), nullable=True),
        sa.Column("product_name", sa.String(length=512), nullable=True),
        sa.Column("color_code", sa.String(length=100), nullable=True),
        sa.Column("color_name", sa.String(length=255), nullable=True),
        sa.Column("size", sa.String(length=100), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.Column("wholesale_price", sa.Float(), nullable=True),
        sa.Column("rrp", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["order_confirmation_id"], ["order_confirmations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_order_confirmation_lines_order_confirmation_id",
        "order_confirmation_lines",
        ["order_confirmation_id"],
    )
    op.create_index(
        "ix_order_confirmation_lines_style_number",
        "order_confirmation_lines",
        ["style_number"],
    )
    op.create_index(
        "ix_order_confirmation_lines_sku",
        "order_confirmation_lines",
        ["sku"],
    )


def downgrade() -> None:
    op.drop_index("ix_order_confirmation_lines_sku", table_name="order_confirmation_lines")
    op.drop_index(
        "ix_order_confirmation_lines_style_number", table_name="order_confirmation_lines"
    )
    op.drop_index(
        "ix_order_confirmation_lines_order_confirmation_id",
        table_name="order_confirmation_lines",
    )
    op.drop_table("order_confirmation_lines")

    op.drop_index("ix_order_confirmations_organisation_id", table_name="order_confirmations")
    op.drop_table("order_confirmations")
