"""add order and season fields

Revision ID: a420ba03447f
Revises: t0u1v2w3x4y5
Create Date: 2026-08-31 10:05:40.920729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a420ba03447f'
down_revision: Union[str, None] = 't0u1v2w3x4y5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import_products', sa.Column('order_number', sa.String(length=100), nullable=True))
    op.add_column('import_products', sa.Column('invoice_number', sa.String(length=100), nullable=True))
    op.add_column('import_products', sa.Column('season_raw', sa.String(length=100), nullable=True))
    op.add_column('import_products', sa.Column('season_normalized', sa.String(length=20), nullable=True))
    op.add_column('imports', sa.Column('invoice_number', sa.String(length=100), nullable=True))
    op.add_column('imports', sa.Column('invoice_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('imports', 'invoice_date')
    op.drop_column('imports', 'invoice_number')
    op.drop_column('import_products', 'season_normalized')
    op.drop_column('import_products', 'season_raw')
    op.drop_column('import_products', 'invoice_number')
    op.drop_column('import_products', 'order_number')
    # ### end Alembic commands ###
