"""add drive_connections table

Revision ID: b133d2455206
Revises: a420ba03447f
Create Date: 2026-08-31 13:52:46.713901

Originally generated against t0u1v2w3x4y5. Re-chained onto a420ba03447f when
the order/season branch and the Drive branch were brought together, so the
history stays a single line — both were still unapplied at that point.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b133d2455206'
down_revision: Union[str, None] = 'a420ba03447f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drive_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('encrypted_access_token', sa.String(length=2048), nullable=False),
    sa.Column('encrypted_refresh_token', sa.String(length=2048), nullable=False),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('root_folder_id', sa.String(length=255), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('connected_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['connected_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organisation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drive_connections')
    # ### end Alembic commands ###
